name: TelegramLink
version: 1.2
main: com.general_viski.telegramlink.TelegramLink
api-version: "1.21"
description: Отправляет сообщения и команды из Minecraft чата в Telegram
author: General_Viski
commands:
  tgbot:
    description: Включение/выключение/перезагрузка/статус бота
    usage: /tgbot <on|off|status|reload>
    permission: telegramlink.toggle
    permission-message: "§cУ вас нет прав на использование этой команды!"
permissions:
  telegramlink.toggle:
    description: Разрешает управление ботом TelegramLink (/tgbot)
    default: op