telegram:
  enabled: true
  bot-token: "YOUR_BOT_TOKEN"
  chat-id: "YOUR_CHAT_ID"
  # Формат сообщений из чата Minecraft
  message-format: |-
    💬 <b>Сообщение из Minecraft</b>
    👤 <b>Игрок:</b> {player}
    📝 <b>Текст:</b> {message}
    🕒 <b>Время:</b> {time}

  # Формат сообщений о выполненных командах
  command-format: |-
    ⚙ <b>Команда в Minecraft</b>
    👤 <b>Игрок:</b> {player}
    🔧 <b>Команда:</b> `{command}`
    🕒 <b>Время:</b> {time}

  # Формат сообщений о попытке выполнения команды без прав
  denied-command-format: |-
    ⚠ <b>Попытка выполнения команды без прав</b>
    👤 <b>Игрок:</b> {player}
    🔧 <b>Команда:</b> `{command}`
    🕒 <b>Время:</b> {time}
    ❗ <b>Статус:</b> Доступ запрещен

  # Формат информации об игроке
  player-info-format: |-
    📊 <b>Информация об игроке</b> {player}
    🎮 <b>Статус:</b> {status}
    🕒 <b>Дата регистрации:</b> {first-played}
    ⏱ <b>Общее время игры:</b> {play-time}
    📍 <b>Последний вход:</b> {last-played}
    🌍 <b>Мир:</b> {world}
    🏷 <b>UUID:</b> `{uuid}`
  allowed-ids:
        - 123456789  # ID администратора 1
        - 987654321  # ID администратора 2