telegram:
  enabled: true
  bot-token: "YOUR_BOT_TOKEN"
  chat-id: "YOUR_CHAT_ID"
  # Формат сообщений из чата Minecraft
  message-format: |-
    💬 *Сообщение из Minecraft*
    👤 *Игрок:* {player}
    📝 *Текст:* {message}
    🕒 *Время:* {time}

  # Формат сообщений о выполненных командах
  command-format: |-
    ⚙ *Команда в Minecraft*
    👤 *Игрок:* {player}
    🔧 *Команда:* `{command}`
    🕒 *Время:* {time}

  # Формат сообщений о попытке выполнения команды без прав
  denied-command-format: |-
    ⚠ *Попытка выполнения команды без прав*
    👤 *Игрок:* {player}
    🔧 *Команда:* `{command}`
    🕒 *Время:* {time}
    ❗ *Статус:* Доступ запрещен

  # Формат информации об игроке
  player-info-format: |-
    📊 *Информация об игроке* {player}
    🎮 *Статус:* {status}
    🕒 *Дата регистрации:* {first-played}
    ⏱ *Общее время игры:* {play-time}
    📍 *Последний вход:* {last-played}
    🌍 *Мир:* {world}
    🏷 *UUID:* `{uuid}`
  allowed-ids:
        - 123456789  # ID администратора 1
        - 987654321  # ID администратора 2